### ISSUE TITLE
Reload crash

### ISSUE THREAD

**Issue by xMikux** [zetastormy/deluxe-hub#16]
### Describe the bug

When use /akropolis reload, the server will immediately crash.

### Link to latest.log file

https://mclo.gs/3aZxrlc

### Steps to reproduce

1. Install akropolis into server
2. Type `/akropolis reload`
3. Send and crash!

### Expected behavior

Can normaly reload the plugins without crash

### Technical information

Server software: Paper
Server version: 1.21-109-master@5a5035b
Plugin version: Akropolis 1.5.3

**Comment by zetastormy** [comment]
I'm aware of this issue and it has been already fixed in the develop branch (see commit c3d8413). In the meantime you can use the JAR I attached to this comment that is compiled against the last version of the develop branch. Thank you for reporting!

[Akropolis-1.5.3.zip](https://github.com/user-attachments/files/16353558/Akropolis-1.5.3.zip)

**Comment by xMikux** [comment]
Thanks!
